export enum API_STATUS_CODES {
	REQUEST_SUCCESS = "00",
	NOT_FOUND = "57",
	STATUS_400 = "49",
}

	export enum AUTH_STATUS_CODES {
		ONBOARD_SUCCESS = "02",
		LOGIN_SUCCESS = "00",
		REFRESH_TOKEN_SUCCESS = "05",
		LOGIN_INVALID_CREDENTIALS = "11",
	}
